service: awsreko

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  memorySize: 128
  lambdaHashingVersion: 20201221
  environment:
    BOTO_ACCESS_KEY_ID: ${env:BOTO_ACCESS_KEY_ID}
    BOTO_SECRET_ACCESS_KEY: ${env:BOTO_SECRET_ACCESS_KEY}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    S3_BUCKET_REGION: ${env:S3_BUCKET_REGION}

plugins:
- serverless-wsgi
- serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3
  wsgi:
    app: app.app
    packRequirements: false

functions:
  index:
    handler: wsgi.handler
    events:
      - http:
          path: ""
          method: get
          cors: true
  url:
    handler: wsgi.handler
    events:
      - http:
          path: url
          method: get
          cors: true
  labels:
    handler: wsgi.handler
    events:
      - http:
          path: labels
          method: get
          cors: true

configValidationMode: error